name = "catatan-hugo"
license = "MIT"
licenselink = "https://github.com/bect/catatan-hugo/blob/master/LICENSE"
description = "Catatan Hugo is a vintage, gritty, archival Hugo theme inspired by typewriters, coffee stains, and 1970s dossiers. Features a dedicated Web Worker-powered search and minimalist typography."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/bect/catatan-hugo"

# If you have a running demo of the theme.
demosite = "https://bect.github.io/catatan-hugo/"

tags = ["blog", "portfolio", "minimalist", "vintage", "typewriter", "dossier", "archive"]
features = ["search", "responsive", "dark mode"]

# If the theme has a single author
[author]
    name = "bect"
    homepage = "https://github.com/bect"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.165.0"