name = "Catatan Hugo"
license = "MIT"
licenselink = "https://github.com/bect/catatan-hugo/blob/master/LICENSE"
description = "Catatan Hugo adalah tema Hugo yang mengusung gaya arsip klasik, kasar, dan vintage, terinspirasi oleh mesin tik, noda kopi, dan dokumen arsip tahun 1970-an. Memiliki fitur pencarian khusus menggunakan Web Worker dan tipografi minimalis."

# Halaman utama tema, di mana kode sumber dapat ditemukan.
homepage = "https://github.com/bect/catatan-hugo"

# Jika Anda memiliki demo yang berjalan untuk tema ini.
demosite = "https://bect.github.io/catatan-hugo/"

tags = ["blog", "portfolio", "minimalist", "vintage", "typewriter", "dossier", "archive"]
features = ["search", "responsive", "dark mode"]

# Jika tema memiliki satu penulis
[author]
    name = "bect"
    homepage = "https://github.com/bect"
